#!/usr/bin/env python3
"""
Track every proposed trade for forward validation.

Files (under DATA_DIR, default ./data):
  trade_setups.jsonl   — one row per proposed trade (+ scan heartbeats)
  trade_tracker.csv    — flat export (regenerated by report)

Usage:
  python trade_tracker.py --fill      # update 1d/5d/10d + stop/target hits
  python trade_tracker.py --report    # print summary + write TRACKING_REPORT.md
"""
from __future__ import annotations

import argparse
import csv
import json
import os
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

import pandas as pd
import yfinance as yf

from chain_setups import TradeSetup
from momentum_chain import MomentumScanResult

DATA_DIR = os.getenv("DATA_DIR", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data"))
SETUP_FILE = os.path.join(DATA_DIR, "trade_setups.jsonl")
REPORT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "TRACKING_REPORT.md")
CSV_FILE = os.path.join(DATA_DIR, "trade_tracker.csv")


def _ensure_dir() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)


def load_all() -> List[Dict[str, Any]]:
    if not os.path.exists(SETUP_FILE):
        return []
    out = []
    with open(SETUP_FILE) as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return out


def _dedupe_trades(trades: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Keep latest row per (scan_time, ticker, direction, setup_type)."""
    seen: Dict[tuple, Dict[str, Any]] = {}
    for t in sorted(trades, key=lambda x: x.get("logged_at", "")):
        key = (
            (t.get("scan_time") or "")[:16],
            t.get("ticker", "").upper(),
            t.get("direction", ""),
            t.get("setup_type", ""),
        )
        seen[key] = t
    return list(seen.values())


def save_all(records: List[Dict[str, Any]]) -> None:
    _ensure_dir()
    with open(SETUP_FILE, "w") as fh:
        for rec in records:
            fh.write(json.dumps(rec) + "\n")


def log_proposed_trades(
    result: MomentumScanResult,
    setups: List[TradeSetup],
    telegram_sent: bool = False,
    alert_mode: str = "actionable",
) -> int:
    """Append proposed trades (and a scan heartbeat). Returns count logged."""
    _ensure_dir()
    n = 0
    scan_id = datetime.now().strftime("%Y%m%d%H%M%S")

    for s in setups:
        rec = {
            "trade_id": f"{scan_id}-{s.ticker}-{s.setup_type[:3]}",
            "logged_at": datetime.now().isoformat(),
            "scan_time": result.scan_time,
            "scan_id": scan_id,
            "alert_mode": alert_mode,
            "telegram_sent": telegram_sent,
            "status": "open",
            **s.to_dict(),
            "outcomes": {},
        }
        with open(SETUP_FILE, "a") as fh:
            fh.write(json.dumps(rec) + "\n")
        n += 1

    heartbeat = {
        "trade_id": f"{scan_id}-scan",
        "logged_at": datetime.now().isoformat(),
        "scan_time": result.scan_time,
        "scan_id": scan_id,
        "setup_type": "scan_heartbeat",
        "proposed_count": len(setups),
        "telegram_sent": telegram_sent,
        "universe_size": result.universe_size,
        "chains": len(result.chains),
    }
    with open(SETUP_FILE, "a") as fh:
        fh.write(json.dumps(heartbeat) + "\n")
    return n


def _price_on(ticker: str, date_str: str) -> Optional[float]:
    try:
        start = pd.Timestamp(date_str) - timedelta(days=5)
        end = pd.Timestamp(date_str) + timedelta(days=15)
        df = yf.Ticker(ticker).history(start=start, end=end, auto_adjust=True)
        if df is None or df.empty:
            return None
        if df.index.tz is not None:
            df.index = df.index.tz_localize(None)
        idx = df.index.get_indexer([pd.Timestamp(date_str)], method="nearest")[0]
        return float(df["Close"].iloc[idx])
    except Exception:
        return None


def _ohlc_after(ticker: str, from_date: str, days: int = 10) -> Optional[pd.DataFrame]:
    try:
        start = pd.Timestamp(from_date) - timedelta(days=2)
        end = pd.Timestamp(from_date) + timedelta(days=days + 5)
        df = yf.Ticker(ticker).history(start=start, end=end, auto_adjust=True)
        if df is None or df.empty:
            return None
        if df.index.tz is not None:
            df.index = df.index.tz_localize(None)
        base = pd.Timestamp(from_date)
        return df[df.index >= base].head(days + 1)
    except Exception:
        return None


def _fwd_return(ticker: str, from_date: str, days: int) -> Optional[float]:
    p0 = _price_on(ticker, from_date)
    if not p0 or p0 <= 0:
        return None
    try:
        end = pd.Timestamp(from_date) + timedelta(days=days + 5)
        start = pd.Timestamp(from_date) - timedelta(days=2)
        df = yf.Ticker(ticker).history(start=start, end=end, auto_adjust=True)
        if df is None or len(df) < 2:
            return None
        if df.index.tz is not None:
            df.index = df.index.tz_localize(None)
        idx = df.index.get_indexer([pd.Timestamp(from_date)], method="nearest")[0]
        exit_idx = min(len(df) - 1, idx + days)
        if exit_idx <= idx:
            return None
        p1 = float(df["Close"].iloc[exit_idx])
        return round((p1 / p0 - 1) * 100, 2)
    except Exception:
        return None


def _signed(direction: str, raw: Optional[float]) -> Optional[float]:
    if raw is None:
        return None
    return raw if direction == "BUY" else -raw


def _stop_target_hit(
    ticker: str,
    from_date: str,
    direction: str,
    entry: float,
    stop: float,
    target: float,
    max_days: int = 10,
) -> Dict[str, Any]:
    out: Dict[str, Any] = {
        "stop_hit": None,
        "target_hit": None,
        "days_to_stop": None,
        "days_to_target": None,
    }
    if entry <= 0 or stop <= 0 or target <= 0:
        return out
    df = _ohlc_after(ticker, from_date, max_days)
    if df is None or len(df) < 2:
        return out
    for i in range(1, len(df)):
        low = float(df["Low"].iloc[i])
        high = float(df["High"].iloc[i])
        if direction == "BUY":
            if out["stop_hit"] is None and low <= stop:
                out["stop_hit"] = True
                out["days_to_stop"] = i
            if out["target_hit"] is None and high >= target:
                out["target_hit"] = True
                out["days_to_target"] = i
        else:
            if out["stop_hit"] is None and high >= stop:
                out["stop_hit"] = True
                out["days_to_stop"] = i
            if out["target_hit"] is None and low <= target:
                out["target_hit"] = True
                out["days_to_target"] = i
    if out["stop_hit"] is None:
        out["stop_hit"] = False
    if out["target_hit"] is None:
        out["target_hit"] = False
    return out


def update_outcomes(min_age_days: int = 1) -> int:
    """Fill forward returns and stop/target hits on open trades."""
    records = load_all()
    if not records:
        return 0
    today = datetime.now().date()
    updated = 0
    for rec in records:
        if rec.get("setup_type") in ("scan_heartbeat", "none"):
            continue
        if not rec.get("ticker"):
            continue
        d_str = (rec.get("scan_time") or rec.get("logged_at", ""))[:10]
        if not d_str:
            continue
        try:
            signal_date = datetime.strptime(d_str, "%Y-%m-%d").date()
        except ValueError:
            continue
        age = (today - signal_date).days
        if age < min_age_days:
            continue

        ticker = rec["ticker"]
        direction = rec.get("direction", "BUY")
        oc = rec.get("outcomes") or {}
        needs = oc.get("ret_10d") is None or oc.get("stop_hit") is None
        if not needs and rec.get("status") == "closed":
            continue

        entry = float(rec.get("entry_price") or 0)
        stop = float(rec.get("stop_loss") or 0)
        target = float(rec.get("target_price") or 0)

        oc["ret_1d"] = _signed(direction, _fwd_return(ticker, d_str, 1))
        if age >= 5:
            oc["ret_5d"] = _signed(direction, _fwd_return(ticker, d_str, 5))
        if age >= 10:
            oc["ret_10d"] = _signed(direction, _fwd_return(ticker, d_str, 10))

        if age >= 1 and entry > 0:
            hits = _stop_target_hit(ticker, d_str, direction, entry, stop, target)
            oc.update(hits)

        # Mark closed after 10d or if stop/target hit
        if age >= 10 or oc.get("stop_hit") or oc.get("target_hit"):
            rec["status"] = "closed"
        else:
            rec["status"] = "open"

        rec["outcomes"] = oc
        rec["outcomes_updated"] = datetime.now().isoformat()
        updated += 1

    if updated:
        save_all(records)
    export_csv(records)
    return updated


def export_csv(records: Optional[List[Dict[str, Any]]] = None) -> str:
    records = records if records is not None else load_all()
    trades = _dedupe_trades([
        r for r in records
        if r.get("ticker") and r.get("setup_type") not in ("scan_heartbeat", "none")
    ])
    if not trades:
        return CSV_FILE
    _ensure_dir()
    fields = [
        "trade_id", "scan_time", "setup_type", "direction", "ticker", "leader",
        "entry_price", "stop_loss", "target_price", "corr", "hit_rate_oos",
        "telegram_sent", "status",
        "ret_1d", "ret_5d", "ret_10d", "stop_hit", "target_hit", "thesis",
    ]
    with open(CSV_FILE, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for r in trades:
            row = {**r, **(r.get("outcomes") or {})}
            w.writerow(row)
    return CSV_FILE


def write_report() -> str:
    records = load_all()
    trades = _dedupe_trades([
        r for r in records
        if r.get("ticker") and r.get("setup_type") not in ("scan_heartbeat", "none")
    ])
    heartbeats = [r for r in records if r.get("setup_type") == "scan_heartbeat"]

    closed = [t for t in trades if t.get("status") == "closed"]
    open_t = [t for t in trades if t.get("status") != "closed"]

    def _wins(ts: List[Dict], key: str = "ret_5d") -> tuple:
        vals = [(t, (t.get("outcomes") or {}).get(key)) for t in ts]
        vals = [(t, v) for t, v in vals if v is not None]
        if not vals:
            return 0, 0, 0.0
        wins = sum(1 for _, v in vals if v > 0)
        avg = sum(v for _, v in vals) / len(vals)
        return wins, len(vals), avg

    w5, n5, avg5 = _wins(closed, "ret_5d")

    lines = [
        "# Trade tracking report",
        "",
        f"> Generated: **{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}**",
        f"> Log file: `{SETUP_FILE}`",
        f"> CSV: `{CSV_FILE}`",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Scans logged | {len(heartbeats)} |",
        f"| Proposed trades | {len(trades)} |",
        f"| Open | {len(open_t)} |",
        f"| Closed (10d or stop/target) | {len(closed)} |",
    ]
    if n5:
        lines.append(f"| Closed with 5d outcome | {w5}/{n5} wins ({100*w5/n5:.0f}%), avg {avg5:+.2f}% |")

    lines.extend(["", "## Open trades", ""])
    if open_t:
        lines.append("| ID | Date | Type | Dir | Ticker | Entry | Stop | Target | Telegram |")
        lines.append("|----|------|------|-----|--------|-------|------|--------|----------|")
        for t in sorted(open_t, key=lambda x: x.get("scan_time", ""), reverse=True):
            lines.append(
                f"| {t.get('trade_id','')} | {(t.get('scan_time') or '')[:10]} | "
                f"{t.get('setup_type','')} | {t.get('direction','')} | {t.get('ticker','')} | "
                f"${t.get('entry_price',0):.2f} | ${t.get('stop_loss',0):.2f} | "
                f"${t.get('target_price',0):.2f} | {'yes' if t.get('telegram_sent') else 'no'} |"
            )
    else:
        lines.append("_None — run scans on a schedule to build history._\n")

    lines.extend(["", "## Closed trades (with outcomes)", ""])
    if closed:
        lines.append(
            "| Date | Type | Dir | Ticker | 1d | 5d | 10d | Stop hit | Target hit | Thesis |"
        )
        lines.append("|------|------|-----|--------|----|----|-----|----------|------------|--------|")
        for t in sorted(closed, key=lambda x: x.get("scan_time", ""), reverse=True):
            o = t.get("outcomes") or {}
            def _p(k):
                v = o.get(k)
                return f"{v:+.1f}%" if isinstance(v, (int, float)) else "—"
            lines.append(
                f"| {(t.get('scan_time') or '')[:10]} | {t.get('setup_type','')} | "
                f"{t.get('direction','')} | {t.get('ticker','')} | {_p('ret_1d')} | {_p('ret_5d')} | "
                f"{_p('ret_10d')} | {o.get('stop_hit', '—')} | {o.get('target_hit', '—')} | "
                f"{(t.get('thesis') or '')[:50]}… |"
            )
    else:
        lines.append("_No closed trades yet — outcomes fill after 1–10 days. Run `python trade_tracker.py --fill`._\n")

    lines.extend([
        "",
        "## Commands",
        "",
        "```bash",
        "python trade_tracker.py --fill     # refresh outcomes",
        "python trade_tracker.py --report   # refresh this file",
        "python chain_ping.py             # one scan (logs trades)",
        "```",
        "",
    ])
    text = "\n".join(lines)
    with open(REPORT_FILE, "w") as fh:
        fh.write(text)
    return REPORT_FILE


def main() -> None:
    p = argparse.ArgumentParser(description="Track proposed chain trades")
    p.add_argument("--fill", action="store_true", help="Update outcomes from market data")
    p.add_argument("--report", action="store_true", help="Write TRACKING_REPORT.md + CSV")
    args = p.parse_args()
    if args.fill:
        n = update_outcomes()
        print(f"Updated {n} trade(s) → {SETUP_FILE}")
    if args.report or not (args.fill):
        path = write_report()
        print(f"Report → {path}")
        export_csv()
        print(f"CSV → {CSV_FILE}")


if __name__ == "__main__":
    main()
